# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 04:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('statsy', '0002_auto_20150222_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsyevent',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='statsyevent',
            name='name',
            field=models.CharField(max_length=30, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='statsygroup',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='statsygroup',
            name='name',
            field=models.CharField(max_length=30, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='statsyobject',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='statsyobject',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='statsyobject',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statsy_object_list', to='statsy.StatsyEvent', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='statsyobject',
            name='extra',
            field=jsonfield.fields.JSONField(blank=True, max_length=1024, null=True, verbose_name='extra'),
        ),
        migrations.AlterField(
            model_name='statsyobject',
            name='float_value',
            field=models.FloatField(blank=True, null=True, verbose_name='float value'),
        ),
        migrations.AlterField(
            model_name='statsyobject',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statsy_object_list', to='statsy.StatsyGroup', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='statsyobject',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='statsyobject',
            name='text_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='text value'),
        ),
        migrations.AlterField(
            model_name='statsyobject',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='statsyobject',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statsy_object_list', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterIndexTogether(
            name='statsyobject',
            index_together=set([('content_type', 'object_id', 'user')]),
        ),
    ]
